version: "3"
services:
  server:
    build: .
    environment:
      - APP_ENV=development
    volumes:
      - .:/go/src/github.com/noppawitt/admintools
    ports:
      - 5000:5000
  # db:
  #   image: microsoft/mssql-server-linux:2017-latest
  #   restart: always
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: Admin1234
  #   ports:
  #     - 1433:1433
