// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import repository "github.com/noppawitt/admintools/repository"

// ParameterService is an autogenerated mock type for the ParameterService type
type ParameterService struct {
	mock.Mock
}

// Repo provides a mock function with given fields:
func (_m *ParameterService) Repo() repository.ParameterRepository {
	ret := _m.Called()

	var r0 repository.ParameterRepository
	if rf, ok := ret.Get(0).(func() repository.ParameterRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ParameterRepository)
		}
	}

	return r0
}
